version: 2.1
jobs:
  upload-to-venus:
    docker:
      image: circleci/python:3
    steps:
      - run: make ssh-ok
      - run: make update-backend

workflows:
  CD:
    jobs:
      - upload-to-venus:
        filters:
          branches:
            only:
              - master